## numpy array and basics

In [2]:
import numpy as np

## creating array from list

In [3]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
type(array_1d)  # <class 'numpy.ndarray'>

numpy.ndarray

In [5]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", array_3d)
print(type(array_3d))  # <class 'numpy.ndarray'>

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [ ]:
## Creating arrays of zeros
arr4 = np.zeros((2, 3)) 
print("Array of zeros:\n", arr4)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr5 = np.ones((3, 4))
print("Array of ones:\n", arr5)
type(arr5)  # <class 'numpy.ndarray'>

Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


numpy.ndarray

In [9]:
arr6 = np.arange(10)
print("Array with a range of values:\n", arr6)

Array with a range of values:
 [0 1 2 3 4 5 6 7 8 9]


In [10]:
arr7 = np.arange(5,20)
print("Array with a specific range of values:\n", arr7)

Array with a specific range of values:
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
