In [1]:
import numpy as np
print(np.__version__)

2.4.6


In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [6]:
arr3 = np.arange(24).reshape(6, 4)
print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## for getting how many dimension have that array using array.ndim

In [7]:
arr3.ndim

2

## ravel() function is used to conevert hight dimension array in 1D array

In [8]:
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Trasnpose function function convert column two row and row as column

In [9]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
arr3.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [11]:
a1 = np.arange(12, 18).reshape(2, 3)
a1

array([[12, 13, 14],
       [15, 16, 17]])

In [12]:
a2 = np.arange(6).reshape(2, 3)
a2

array([[0, 1, 2],
       [3, 4, 5]])

## hstack() function used to add two array in numpy
# exmaple arr1, arr1 u want to add those then 
# np.hstack((arr1, arr2)) this will add horizontally

In [13]:
np.hstack((a1, a2))

array([[12, 13, 14,  0,  1,  2],
       [15, 16, 17,  3,  4,  5]])

# vstack((arr1, arr2)) this will add vertically

In [14]:
np.vstack((a1, a2))

array([[12, 13, 14],
       [15, 16, 17],
       [ 0,  1,  2],
       [ 3,  4,  5]])

## np.vsplit() and np.hsplit() spliting array that accept first parameter is array and second one is number how may split you want

In [15]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
np.hsplit(arr3, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [18]:
np.vsplit(arr3, 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]