In [15]:
import numpy as np
print(np.__version__)

2.4.6


In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [17]:
arr3 = np.arange(24).reshape(6, 4)
print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## for getting how many dimension have that array using array.ndim

In [18]:
arr3.ndim

2

## ravel() function is used to conevert hight dimension array in 1D array

In [19]:
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Trasnpose function function convert column two row and row as column

In [20]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
arr3.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [22]:
a1 = np.arange(12, 18).reshape(2, 3)
a1

array([[12, 13, 14],
       [15, 16, 17]])

In [23]:
a2 = np.arange(6).reshape(2, 3)
a2

array([[0, 1, 2],
       [3, 4, 5]])

## hstack() function used to add two array in numpy
# exmaple arr1, arr1 u want to add those then 
# np.hstack((arr1, arr2)) this will add horizontally

In [24]:
np.hstack((a1, a2))

array([[12, 13, 14,  0,  1,  2],
       [15, 16, 17,  3,  4,  5]])

# vstack((arr1, arr2)) this will add vertically

In [25]:
np.vstack((a1, a2))

array([[12, 13, 14],
       [15, 16, 17],
       [ 0,  1,  2],
       [ 3,  4,  5]])

## np.vsplit() and np.hsplit() spliting array that accept first parameter is array and second one is number how may split you want

In [26]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
np.hsplit(arr3, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [28]:
np.vsplit(arr3, 3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [29]:
arr8 = np.arange(24).reshape(6,4)

In [30]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
# fancy indexing
arr8[[0, 2, 4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

# Indexing with boolean arrays

In [33]:
arr9 = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr9

array([[96, 42, 48, 33, 41],
       [96, 18, 50,  4, 32],
       [99, 87, 71, 91, 54],
       [ 3, 39, 18, 30, 50]])

# Boolean array
arr > 50

In [36]:
(arr9 > 50).shape

(4, 5)

In [37]:
arr9>50

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

#Indexing using boolean array
arr[arr>50]

In [ ]:
# this will give us the values which are greater than 50
arr9[arr9 > 50]

array([96, 96, 99, 87, 71, 91, 54])