## numpy array and basics

In [22]:
import numpy as np

## creating array from list

In [23]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [24]:
type(array_1d)  # <class 'numpy.ndarray'>

numpy.ndarray

In [25]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", array_3d)
print(type(array_3d))  # <class 'numpy.ndarray'>

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [26]:
## Creating arrays of zeros
arr4 = np.zeros((2, 3)) 
print("Array of zeros:\n", arr4)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
arr5 = np.ones((3, 4))
print("Array of ones:\n", arr5)
type(arr5)  # <class 'numpy.ndarray'>

Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


numpy.ndarray

In [28]:
arr6 = np.arange(10)
print("Array with a range of values:\n", arr6)

Array with a range of values:
 [0 1 2 3 4 5 6 7 8 9]


In [29]:
arr7 = np.arange(5,20)
print("Array with a specific range of values:\n", arr7)

Array with a specific range of values:
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
## indentity matrix
identity_matrix = np.eye(4)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
arr9 = np.identity(5)
print("Identity Matrix using np.identity:\n", arr9)

Identity Matrix using np.identity:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
arr10 = np.linspace(0, 1, 5)
print("Array with evenly spaced values between 0 and 1:\n", arr10)
arr11 = np.linspace(10, 20, 10)
print("Array with evenly spaced values between 10 and 20:\n", arr11)

Array with evenly spaced values between 0 and 1:
 [0.   0.25 0.5  0.75 1.  ]
Array with evenly spaced values between 10 and 20:
 [10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [33]:
x = np.linspace(0, 2*np.pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

## copy 

In [34]:
ar1 = np.array([1, 2, 3, 4, 5])
ar1 

array([1, 2, 3, 4, 5])

In [35]:
ar2 = ar1.copy()
ar2

array([1, 2, 3, 4, 5])

## Numpy array properties and attributes
1. Shape
2. nDim
3. Size
4. Itemsize
5. Dtype
6. astype()


In [36]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr3d)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [37]:
a1 = np.array([1, 2, 3])
a1.shape  # (3,)

(3,)

In [38]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2.shape  # (2, 3)

(2, 3)

In [41]:
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 
a3.shape  # (2, 2, 2)
a3.ndim

3

In [42]:
a2.size

6

In [43]:
a2.itemsize

8

In [44]:
x.dtype

dtype('float64')

In [45]:
a2.dtype

dtype('int64')

In [49]:
a2.astype('float')
print("Array a2 with float data type:\n", a2.astype('float'))

Array a2 with float data type:
 [[1. 2. 3.]
 [4. 5. 6.]]


## Numpy array vs Pythom lists
1. faster
2. Convenient
3. Less memory

In [50]:
lista = range(100)
arra = np.arange(100)

In [51]:
import sys

In [52]:
print(sys.getsizeof(87)*len(lista))  # Size of list in bytes

2800


In [53]:
print(arra.itemsize * arra.size)  # Size of NumPy array in bytes

800


In [54]:
import time

In [59]:
x = range(10000000)
y = range(10000000, 20000000)
start_time = time.time()

c = [x+y for x,y in zip(x,y)]

print("Time taken for list comprehension:", time.time() - start_time)


Time taken for list comprehension: 0.2859339714050293


In [60]:
x1 = np.arange(10000000)
y1 = np.arange(10000000, 20000000)
start_time = time.time()

c1 = x1 + y1

print("Time taken for NumPy array operations:", time.time() - start_time)
# print(c)

Time taken for NumPy array operations: 0.02692699432373047


## Indexing, Slicing, Iteration

In [69]:
arr01 = np.arange(24).reshape(6,4)
arr01

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## reshap function for reshape matrix 

In [89]:
arr01

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [90]:
for i in arr01:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [91]:
for i in np.nditer(arr01):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## Numpy Array Opertaion

In [94]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([4, 5, 6, 7, 8, 9])

print(arr1)
print(arr2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [95]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [ ]:
# vector multiplication
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [ ]:
# scalar multiplication
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [99]:
arr2 > 3

array([ True,  True,  True,  True,  True,  True])

In [100]:
nparray1 = np.arange(6).reshape(2,3)
nparray2 = np.arange(6,12).reshape(3,2)

In [101]:
nparray1.dot(nparray2)

array([[ 28,  31],
       [100, 112]])

In [102]:
nparray2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [103]:
nparray2.max()

np.int64(11)

In [104]:
nparray2.min()

np.int64(6)

In [105]:
nparray2.min(axis=0)  # Minimum along columns

array([6, 7])

In [106]:
nparray2.min(axis=1)  # Minimum along rows

array([ 6,  8, 10])